TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += ambrell_easy_heat.db
DB += error_setter.db
DATA += ambrell_easy_heat.proto

#=======================================
include $(TOP)/configure/RULES
